file(READ "${SOURCE_DIR}/tests/conformance/vectors/ocp_hbf_v0_7_vectors.json" VECTORS)
file(READ "${SOURCE_DIR}/tests/conformance/spec_gap_manifest.json" GAPS)
file(READ "${SOURCE_DIR}/tests/conformance/evidence-manifest.schema.json" SCHEMA)

foreach(REQUIRED IN ITEMS OCP-5.3-64B OCP-5.4-DLU OCP-TABLES-12-13 OCP-SPEED-GRADE-3)
  string(FIND "${VECTORS}" "${REQUIRED}" FOUND)
  if(FOUND EQUAL -1)
    message(FATAL_ERROR "missing frozen OCP vector ${REQUIRED}")
  endif()
endforeach()

foreach(REQUIRED IN ITEMS GAP-001 GAP-003 GAP-006 GAP-009 GAP-010 BLOCKED_SPEC EXTERNAL_DEPENDENCY)
  string(FIND "${GAPS}" "${REQUIRED}" FOUND)
  if(FOUND EQUAL -1)
    message(FATAL_ERROR "missing required release gap/status ${REQUIRED}")
  endif()
endforeach()

foreach(REQUIRED IN ITEMS experiment_id evidence_level candidate_level production_path config_hash workload_hash spec_locators open_gaps)
  string(FIND "${SCHEMA}" "${REQUIRED}" FOUND)
  if(FOUND EQUAL -1)
    message(FATAL_ERROR "evidence schema omits ${REQUIRED}")
  endif()
endforeach()
